export const siteMetadata = {
  name: "Harshit Waldia",
  title: "Harshit Waldia — AI/ML Engineer",
  description:
    "AI/ML Engineer specializing in LLMs, RAG systems, Computer Vision, and production-grade backend architectures with Python and FastAPI.",
  url: "https://harshitwaldia.github.io/e-Portfolio/",
  ogImage: "/images/profile/harshit.jpg",
  author: {
    name: "Harshit Waldia",
    email: "harshitwaldia112@gmail.com",
    github: "https://github.com/harshitwaldia",
    linkedin: "https://linkedin.com/in/harshit-waldia",
    twitter: "https://github.com/harshitwaldia",
    calendly: "mailto:harshitwaldia112@gmail.com",
    phone: "7060546501",
    location: "Dehradun, Uttarakhand, India",
  },
  keywords: [
    "Harshit Waldia",
    "AI/ML Engineer",
    "Machine Learning",
    "Generative AI",
    "LLM",
    "RAG",
    "Computer Vision",
    "FastAPI",
    "Python",
    "PyTorch",
    "Deep Learning",
    "Portfolio",
    "Info Origin Inc.",
    "SLOG Solutions",
  ],
} as const;

